defmodule ReactRenderDemoWeb.PageController do
  use ReactRenderDemoWeb, :controller

  def index(conn, _params) do
    component_path = "#{File.cwd!()}/assets/js/containers/ServerContainer.js"
    {app, tags} = ReactRender.render_root(component_path, %{location: conn.request_path})

    # tags represents the style, script, and link tags generated by loadable-components ChunkExtractor
    render(conn, "index.html", app: app, tags: tags)
  end
end
